version: "3.9"
services:
  db:
    build: ./db
    env_file:
      - ./env/db.env
  api:
    image: docker.io/dadard29/passive-dns-api:latest
    env_file:
      - ./env/api.env
    ports:
      - "8080:8080"
  front:
    build: ./front
    ports:
      - "8081:80"
  scheduler:
    image: docker.io/dadard29/passive-dns-scheduler:latest
    env_file:
      - ./env/scheduler.env
