image: docker:stable
stages:
  - build

services:
  - docker:dind

build:
  only:
    - tags
  stage: build
  script:
    - docker info
    - echo "registering with $REGISTRY_USERNAME $REGISTRY_PASSWORD"
    - echo version set to $CI_COMMIT_TAG
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME --password-stdin registry.gitlab.com
    - docker build -t $IMAGE_NAME --build-arg VERSION=$CI_COMMIT_TAG .
    - docker push $IMAGE_NAME
