image: docker:stable
stages:
  - build

services:
  - docker:dind

build-and-test:
  only:
    - tags
  stage: build
  script:
    - docker info
    - echo "registering with $REGISTRY_USERNAME $REGISTRY_PASSWORD"
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD registry.gitlab.com
    - echo version set to $CI_COMMIT_TAG
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
