image: docker:stable
stages:
  - build

services:
  - docker:dind

build:
  only:
    - tags
  stage: build
  script:
    - docker info
    - echo "registering with $REGISTRY_USERNAME $REGISTRY_PASSWORD"
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME --password-stdin registry.gitlab.com
    - echo version set to $CI_COMMIT_TAG
    - docker build -t $IMAGE_NAME --build-arg VERSION=$CI_COMMIT_TAG --build-arg JOB_URL=$CI_JOB_URL --build-arg COMMIT_SHA=$CI_COMMIT_SHORT_SHA --build-arg ARANGO_USERNAME=$ARANGO_USERNAME --build-arg ARANGO_PASSWORD=$ARANGO_PASSWORD --build-arg JWT_SECRET_KEY=$JWT_SECRET_KEY .
    - docker push $IMAGE_NAME
