# This is a basic workflow to help you get started with Actions

name: Docs Publishing

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
      
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          
      - name: Deploy to pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: docs
          folder: ./frontend/dist
          token: ${{ secrets.PAT }}
          repository-name: PassiveDNS/PassiveDNS.github.io
          
      
