# This is a basic workflow to help you get started with Actions

name: Docker Image Publishing

# Controls when the workflow will run
on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Setting up env
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "JOB_URL=https://github.com/PassiveDNS/PassiveDNS/actions/runs/${GITHUB_RUN_ID}" >> $GITHUB_ENV
      
      - name: Logging build args
        run: |
          echo "version: ${VERSION}"
          echo "commit SHA: ${COMMIT_SHA}"
          echo "job URL: ${JOB_URL}"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: dadard29/passive-dns-api,dadard29/passive-dns-scheduler
      
      - name: Build and push API image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: dadard29/passive-dns-api:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_SHA=${{ env.COMMIT_SHA }}
            JOB_URL=${{ env.JOB_URL }}
      
      - name: Build and push scheduler image
        uses: docker/build-push-action@v2
        with:
          context: ./scheduler
          push: true
          tags: dadard29/passive-dns-scheduler:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
